### ISSUE TITLE
Compatibility with symfony/event-dispatcher 4.*

### ISSUE THREAD

**Issue by ilvalerione** [sebdesign/laravel-state-machine#11]
Hello,
I'm trying to install this package but composer give me a incompatible warning with symfony event dispatcher used in winzou/state-machine.

In the composer.json of the winzou package there is the constraint below:

`"symfony/event-dispatcher":    "~2.1|~3.0",`

But Laravel 5.5 ships with symfony/event-dispatcher 4.0.4

How do you use this package in Laravel 5 with this issue from winzou?

**Comment by sebdesign** [comment]
Hi @ilvalerione ,

Thanks for reporting this issue! I propably didn't test this enough with Laravel 5.5.
I will try to fix this today, but if you have a quick fix that you could submit as a PR, I'll merge it.

Someone has asked a similar question in the wizou repo: https://github.com/winzou/state-machine/issues/38

**Comment by ilvalerione** [comment]
I don't know what we can do... 
Winzou should update your dependencies or I need to fork original state-machine package. I'm waiting an answer from winzou. Thanks for link.

**Comment by sebdesign** [comment]
I found this fork which is submitted as a PR.
https://github.com/bpolaszek/state-machine

I guess we could use this repo as a VCS in our composer.json, until the winzou package becomes compatible.

**Comment by sebdesign** [comment]
I've tagged 1.2.4 with support for Laravel 5.6.
