### ISSUE TITLE
Custom exceptions 

### ISSUE THREAD

**Issue by devngl** [sebdesign/laravel-state-machine#16]
Is it possible to define custom exceptions when a transition is rejected during a custom callback?

I would like to translate the message differently depending on the graph.

**Comment by sebdesign** [comment]
The first thing that comes to my mind is that you throw a custom exception in you custom callback.

E.g. In your graph:
```php
'callbacks' => [
    'guard' => [
        'guard_on_submitting' => [
            // call the callback on a specific transition
            'on' => 'submit_changes',
            // will call the method of this class
            'do' => ['MyClass', 'handle'],
            // arguments for the callback
            'args' => ['object', 'event'],
        ],
    ],
],
```

In your class you can access the object as well as the transition event:
```php
class MyClass
{
    public function handle($object, $event)
    {
        $graphName = $event->getStateMachine()->getGraph();
        $transitionName = $event->getTransition();
        $fromState = $event->fromState();

        if ($this->reject()) {
            throw new MyException('My custom message for this graph');
        }

        return true;
    }
}
```
The only downside of this approach is that `$sm->can('submit_changes')` will always throw an exception.
If you want you can give me an example of you custom callback to give you a better solution.

**Comment by devngl** [comment]
The custom exceptions trick worked like a charm for this use case, I can live with the downside. Thanks!

**Comment by MartinP7r** [comment]
@sebdesign , Sorry for hi-jacking this question:  

Would there be a way to throw the exception from inside a policy called via the `guard` config statement?  
E.g. I'd like to show a message to the user via Laravel's `\Response::deny()` (or `$this->deny()` from inside the policy class) but it seems that's not working and I always get a `SMException`.

One reason I'm asking is the added benefit of getting the sessions `User` and the model object injected inside the Policy for that particular model. So handling permission related checks there seems like the best choice.

**Comment by sebdesign** [comment]
@MartinP7r that's an interesting question! That's not possible currently, but I could implement that as a feature.
In the meantime, there is a workaround for this. Instead of a `guard` config, you can use a `before` config statement (do not use both, since the guard will return `false` before).

```php
'callbacks' => [
    'before' => [
        'before_submitting' => [
            'on' => 'submit_changes',
            'do' => ['Gate', 'authorize'],
            'args' => ['"submit"', 'object'],
        ],
    ],
],
```

This statement will call `Gate::authorize('submit', $model)` before applying the `submit_changes` transition.
If you are using `Response::deny()` or `$this->deny()` inside the `submit` method of your policy, the `AuthorizationException` will be thrown. If you return `false` (or nothing), the transition will still be applied.

**Comment by MartinP7r** [comment]
Thank you for the suggestion @sebdesign ! The work-around seems workable, though if you get around to implementing it as a feature, that would probably be cleaner.  

One problem with the workaround would be that I'm losing the possibility to run some logic involving the `TransitionEvent->getContext()` with the `before` config statement. Correct me if I'm wrong, but something like `'args' => ['"submit"', 'object', 'event']` doesn't seem to work. 

```
Too few arguments to function App\Policies\SomePolicy::submit()
```

This time it seems I can make it work with `after` alone.

---

**edit: nevermind, I just realized I can do more than one `before` statement per state and they will fire in order.**

**Comment by sebdesign** [comment]
Oh I think I know what it is. `Gate::authorize()` accepts only 2 parameters: the `$ability` and the `$arguments` which is an array. So in your config you should specify the model and the event arguments as an array: `'args' => ['"submit"', '[object, event]']`. This way it will call: `gate::authorize('submit', [$model, $event])`.

**Comment by MartinP7r** [comment]
Oh wow, I did not realize that. And sorry for the late reply. I'll check this out next week at work!
Thank you as always for being so helpful!
