### ISSUE TITLE
v1.3.1 .. Add support for Laravel 5.8

### ISSUE THREAD

**Issue by bublicov** [sebdesign/laravel-state-machine#18]
v1.3.1 .. Add support for Laravel 5.8 

but no changes on composer.json (

**Comment by sebdesign** [comment]
You're right, I missed something in that commit. Should be fixed in v1.3.2 (just tagged).

**Comment by bublicov** [comment]
oops ..

[InvalidArgumentException]                                                          
Could not find package sebdesign/laravel-state-machine in a version matching 1.3.2

**Comment by bublicov** [comment]
merci
