### ISSUE TITLE
Can't install on a fresh Laravel 7 project

### ISSUE THREAD

**Issue by divan-mt** [sebdesign/laravel-state-machine#35]
I get this error while trying to install this package in a fresh Laravel 7 project.

`    - sebdesign/laravel-state-machine v3.0.0 requires winzou/state-machine ^0.4.0 -> no matching package found.
`

It seems `winzou/state-machine` has latest version [0.3.3](https://github.com/winzou/state-machine/releases/tag/0.3.3) but you require ^0.4.0
Is there anything with this?

**Comment by sebdesign** [comment]
Yes I had the same problem a few days ago, so I put a small upgrade guide on the release page: https://github.com/sebdesign/laravel-state-machine/releases/tag/v3.0.0

Let me know if that fixes the issue.

**Comment by divan-mt** [comment]
Ah I totally missed that. Thank you.
