### ISSUE TITLE
"winzou/state-machine": "^0.4.0"

### ISSUE THREAD

**Issue by Skullbock** [sebdesign/laravel-state-machine#37]
It seems that this dependency doesn't exist:, the 0.4.0 is the bundle, here we require the basic package which is 0.3.0

**Comment by Skullbock** [comment]
Sorry, i just saw it's a dependency you created as an override.
Closing this

**Comment by MartinP7r** [comment]
Thanks @Skullbock, that was also my problem.  

For whoever comes here wondering why there's no version 0.4.0 of `winzou/state-machine`, you need to follow the upgrade guide in https://github.com/sebdesign/laravel-state-machine/releases/tag/v3.0.0 for a temporary workaround to enable the version up for Laravel 7.
