### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by ghost** [sebdesign/laravel-state-machine#40]
sebdesign/laravel-state-machine v3.0.0 requires winzou/state-machine ^0.4.0 -> no matching package found.

apparently the latest version of winzou is 0.3.3 and 0.4 is being required

**Comment by sebdesign** [comment]
Please add the following section to your `composer.json`:

```diff
+ "repositories": [
+     {
+         "type": "vcs",
+         "url": "https://github.com/sebdesign/state-machine"
+     }
+ ]
```
