### ISSUE TITLE
Callback error - Expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by nishantha-kumara** [sebdesign/laravel-state-machine#51]
Development environment

- PHP version: 7.3
- Laravel version: ^6.2
- State machine version: ^2.0

Hello,
I'll try to use the state machine in one of my projects. I have installed and set up the state machine according to the documentation. but when I run the callbacks using the state machine getting an error.

```
PHP Deprecated:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method App/Services/ConsultationSession::afterPatientCancel() should not be called statically in /Volumes/My Files/web-root/sites/sample-projects/laravel-6/vendor/winzou/state-machine/src/SM/Callback/Callback.php on line 75
```

This is my state machine config file.

```

return [
    'consultation' => [
        'class' => 'App\User',
        'graph' => 'consultation',
        'property_path' => 'state',
        'states' => [
            'pending', 'timeout', 'cancelled', 'doctor_confirmed'
        ],
        'transitions' => [
            'timeout' => [
                'from' => ['pending'],
                'to' => 'timeout'
            ],
            'cancel' => [
                'from' => ['pending'],
                'to' => 'cancelled'
            ],
        ],
        'callbacks' => [
            'after' => [
                'after_cancel' => [
                    'on' => 'cancel',
                    'do' => ['App\Services\ConsultationSession', 'afterPatientCancel'],
                    'args' => ['object']
                ],
            ],
        ]
    ],
];

```

And if I change the callback function to **static** or call the function **using an object** (`new App\Services\ConsultationSession()`), the error is solved. 
if I use call back using an object (`new App\Services\ConsultationSession()`), I can't cache the configs.
`Error::("Call to undefined method App\Services\ConsultationSession::__set_state()")`

So what's the issue and how can I solve it? 
Thanks.

**Comment by sebdesign** [comment]
Indeed, now that I'm looking at the code, the callback is executed statically: `call_user_func_array('App\Services\ConsultationSession', 'afterPatientCancel')`, so PHP is expecting a static method.

If you don't want to use a static method, you need to bind the `App\Services\ConsultationSession'` to the Laravel container.
This way, the object will be resolved through the container and your method will be executed correctly.

For example, in your `AppServiceProvider`:

```php
public function register()
{
    // a simple binding
    $this->app->bind(\App\Services\ConsultationSession::class);

    // or a binding with a callback (most common)
    $this->app->bind(\App\Services\ConsultationSession::class, function () {
        return new \App\Services\ConsultationSession(...);
    });
}
```

Instead of the `bind()` you can also use the `singleton()` method to only have one object during the request.

**Comment by nishantha-kumara** [comment]
Thanks for your quick response. Actually, I know both methods. are you plan to fix the issue in the future? 
need to call the **nonstatic method** using the state machine callback (according to the documentation.]).
```
'do' => ['App\Services\ConsultationSession', 'afterPatientCancel'],
```

**Comment by nishantha-kumara** [comment]
> Indeed, now that I'm looking at the code, the callback is executed statically: `call_user_func_array('App\Services\ConsultationSession', 'afterPatientCancel')`, so PHP is expecting a static method.
> 
> If you don't want to use a static method, you need to bind the `App\Services\ConsultationSession'` to the Laravel container.
> This way, the object will be resolved through the container and your method will be executed correctly.
> 
> For example, in your `AppServiceProvider`:
> 
> ```
> public function register()
> {
>     // a simple binding
>     $this->app->bind(\App\Services\ConsultationSession::class);
> 
>     // or a binding with a callback (most common)
>     $this->app->bind(\App\Services\ConsultationSession::class, function () {
>         return new \App\Services\ConsultationSession(...);
>     });
> }
> ```
> 
> Instead of the `bind()` you can also use the `singleton()` method to only have one object during the request.

Thanks for your quick response. Actually, I know both methods. are you plan to fix the issue in the future? 
need to call the **nonstatic method** using the state machine callback (according to the documentation.]).
```
'do' => ['App\Services\ConsultationSession', 'afterPatientCancel'],
```

**Comment by sebdesign** [comment]
It's not an error, it's the way PHP works. `call_user_func_array()` accepts an object or a class name and calls the static or non-static method respectively.

Furthermore, I would not change the way the callbacks work, because some developers may want to call static methods, while others want to call non-static methods. So we need to support both.

The correct way to call a non-static method on an object is to resolve the object from the container, like the service provider.
This way you will be able to use the callback exactly like the documentation: `'do' => ['App\Services\ConsultationSession', 'afterPatientCancel']`

**Comment by nishantha-kumara** [comment]
> It's not an error, it's the way PHP works. `call_user_func_array()` accepts an object or a class name and calls the static or non-static method respectively.
> 
> Furthermore, I would not change the way the callbacks work, because some developers may want to call static methods, while others want to call non-static methods. So we need to support both.
> 
> The correct way to call a non-static method on an object is to resolve the object from the container, like the service provider.
> This way you will be able to use the callback exactly like the documentation: `'do' => ['App\Services\ConsultationSession', 'afterPatientCancel']`

Okay. 
I think you need to add the how-to call static functions and non-static function clearly in your documentation.

**Comment by sebdesign** [comment]
Yes you're right about that! I will update the documentation accordingly.
