### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by CodyPChristian** [sebdesign/laravel-state-machine#54]
Hello, I recently upgraded to Laravel 8 (using Shift) and as soon as I try to use this package it no longer works. I dont get any errors oddly but if I try to transition a state it will fail saying that its not allowed. The only changes is the framework upgrade. I tried this on a fresh Laravel 8 install and the same issue was there. It also seems to be ignoring the guards which is probably the core issue here. Any ideas?

Also here: https://github.com/iben12/laravel-statable/issues/35

**Comment by sebdesign** [comment]
Hello, can you post your `config/state-machine.php` and any related code? I want to replicate this issue with a fresh Laravel installation.

**Comment by CodyPChristian** [comment]
Yes, I did find the issue was my policy file. Here is all of the files: https://gist.github.com/CodyPChristian/db18a5b64fe1e3c5684ea872ae7106dc

What I found is the function had to be $user = null for it to work, if this is removed it stops working, I even replicated this in Laravel 7 as well.

**Comment by sebdesign** [comment]
I think this is related to the guest user. Since you don't have a `User` typehint for the `$user` parameter on the `CheckUserStatePolicy::handle()` method, you need to make it nullable `$user = null`.

https://laravel.com/docs/8.x/authorization#guest-users

**Comment by CodyPChristian** [comment]
Thanks, yes I found this out too and made the change, if I recall I had to do  use `$user = null` in Laravel 7 to get this to work but in Laravel 8 we have guest users option now with `?User $user`.
