### ISSUE TITLE
States/transitions in database

### ISSUE THREAD

**Issue by patryyyck** [sebdesign/laravel-state-machine#55]
Hello,

This package is awsome.

And i have a little question:
In order to have a more "flexible" workflow, is there a way to store (and get) the states and transitions in the database instead of the config file (config/state-machine.php)?

Regards

**Comment by sebdesign** [comment]
Yes that's possible!

Let's say that in your `Order` model you have a `state_machine` column.
The migration would be: `$table->json('state_machine')`.
In the `Order` model you should add this column to your casts: `'state_machine' => 'json'`.
Then you can save the config (states, transitions, callbacks, etc) like this:

```php
$order->state_machine = ['class' => Order::class, 'states' => [...], 'transitions' => [...]];
$order->save();
```

To get the state machine with your config you can add a method to your model.
This method will add the config from the database to the existing configuration.

```php
use Sebdesign\SM\Facade as StateMachine;
use SM\StateMachine\StateMachineInterface;

public function getStateMachine(): StateMachineInterface
{
    // the graph is the id of the model to make it unique for the class
    StateMachine::addConfig($this->state_machine, $this->id);

    // This will get the config for your class and graph
    return StateMachine::get($this, $this->id);
}
```

**Comment by patryyyck** [comment]
Thanks.
That looks great!
I'll try.

But i still wonder something.
In your example, the Order model will have 2 more columns:

- my_status  (the current status of my order)
- state_machine (the available states/transitions)

Maybe the second one can be store in another table/model in order to avoid to have the complete state machine configuration in each row of the Order table.

**Comment by sebdesign** [comment]
You can create another table/model for you state machine configurations. For example:

```php
class OderStateMachine extends Model
{
    protected $casts = ['config' => 'json'];
}

class Order extends Model
{
    public function stateMachine()
   {
        return $this->hasOne(OrderStateMachine::class);
    }

    public function getStateMachine(): StateMachineInterface
    {
        // the graph is the id of the model to make it unique for the class
        StateMachine::addConfig($this->stateMachine->config, $this->id);

        // This will get the config for your class and graph
        return StateMachine::get($this, $this->id);
    }
}

**Comment by patryyyck** [comment]
This is perfect.
I'll try this soon.

Thanks very much
