### ISSUE TITLE
Please support Laravel v6.20

### ISSUE THREAD

**Issue by videni** [sebdesign/laravel-state-machine#63]
I am using  laravel/framework  `v6.20.44` which has 
```
symfony/property-access                   v5.4.11
symfony/event-dispatcher                  v4.4.42
```

But the the ^2.0 of this packages depends on [winzou/state-machine](https://packagist.org/packages/winzou/state-machine): ^0.3.2, which has following dependencies.

```
symfony/event-dispatcher: ~2.1|~3.0
symfony/expression-language: ~2.4|~3.0
symfony/property-access: ~2.1|~3.0
```

**Comment by sebdesign** [comment]
I'll see if I can support this version without many changes.

**Comment by sebdesign** [comment]
So I've checked the version `v2.1.1` of this package, which has these dependencies:
- **laravel/support** `^5.5 | ^6.0`, which means `v6.20.44` is installable
- **winzou/state-machine** `^0.3.2`, which means `v0.3.3` is installable

**winzou/state-machine** `v0.3.3` has these dependencies:
- **symfony/event-dispatcher** `~2.1|~3.0|~4.0`, which means `v4.4.2` is installable
- **symfony/property-access** `~2.1|~3.0|~4.0`, which means `v5.4.11` is **NOT** installable
- **symfony/expression-language** `~2.1|~3.0|~4.0`, which means `v4.4.2` is installable

So the question is, which of your dependencies requires **symfony/property-access** `^5.0`?

**Comment by videni** [comment]
@sebdesign , thanks for the details, It seems it is my fault.
