### ISSUE TITLE
How to use Gate::allows()  ?

### ISSUE THREAD

**Issue by eduardoarandah** [sebdesign/laravel-state-machine#7]
How to use Laravel Gate to further authorize the change in status?
https://laravel.com/docs/5.5/authorization#authorizing-actions-via-gates

For this example, the change in state is valid, but I also need to check if it's authorized

I get this error: 
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Support\Facades\Gate' does not have a method 'allows'

```
// list of all callbacks
        'callbacks'     => [
            // will be called when testing a transition
            'guard'  => [
                'guard_on_sending' => [
                    // call the callback on a specific transition
                    'on'   => 'sending',
                    // will call the method of this class
                    'do'   => ['Gate', 'allows'],
                    // arguments for the callback
                    'args' => ['send_request'],
                ],
            ],

            // will be called before applying a transition
            'before' => [],

            // will be called after applying a transition
            'after'  => [],
        ],
```

Any ideas?

**Comment by eduardoarandah** [comment]
I figured it out!

It would be useful to include in readme

To further autorize the transition using built-in permissions: 

Create a policy, example: StatePolicy

`php artisan make:policy StatePolicy`

This policy receives the object being transitioned and the transition, so we will use it as arguments. 

```php
<?php
namespace App\Policies;

use Gate;
use Illuminate\Auth\Access\HandlesAuthorization;

class StatePolicy
{
    use HandlesAuthorization;
    public function can($object, $event)
    {
        return Gate::allows('transitions.exposicion.' . $event->getTransition());
    }
}

```

In this example, laravel will check current user to have a permission called "transitions.exposicion.nameoftransitionhere'

You have to register that permission as usual.

now we can use it in config/state-machine.php 
```php

'callbacks'     => [
            // will be called when testing a transition
            'guard'  => [
                [
                    // call the callback on a specific transition
                    'on'   => 'enviar_solicitud',
                    // will call the method of this class
                    'do'   => ['\App\Policies\StatePolicy', 'can'],
                    // arguments for the callback
                    'args' => ['object', 'event'],
                ],
            ],
```

in this example, Laravel will check a permission called 'transitions.exposicion.enviar_solicitud'

**Comment by sebdesign** [comment]
Hi @eduardoarandah ,

When I was developing this package, I was thinking how can I integrate Laravel's Gate.
Like your example, one way is to perform a `Gate::allows()` check on the `guard` callback of the state machine.

I think the mistake on your first comment is that you are referencing the gate facade, which cannot be resolved correctly in the callback. Maybe that's something I should fix.

In your second example, you are defining a `Policy` which calls the gate internally. This is a bit redundant, since the policy methods should contain the actual authorization logic.

If you want to call the `transitions.exposicion.enviar_solicitud` gate directly I think you could define your callback like this:

```php
'guard' => [
    [
        'on' => 'enviar_solicitud',
        // We are referencing the actual Gate class instead of the facade
        'do' => [Iluminate\Auth\Access\Gate::class, 'allows'],
        // The first argument will be the name of the gate (notice the quotation marks)
        'args' => ['"transitions.exposicion.enviar_solicitud"', 'event'],
    ],
],
```

**Comment by eduardoarandah** [comment]
Thanks!

Callbacks seems very complicated to figure out by oneself. 
Yes, using a policy is redundant, the guard should be able to call the Gate directly.

Integrating with Laravel Gate would be great! because it lets you use all the nice tools like 
```
blade @can()
$user->can()
middleware('can:permission-name')
Gate::allows()
```


This is how I'm solving Authorizations:

1- Is the user authorized to see the object in its **current** state?

if the state is **published** check 

 `Gate::allows('state-machine.publishing.states.published')`

2- What transitions are authorized for current user?

Step 1: get possible transitions with `getPossibleTransitions()`
```
publish
delete
save_draft
```

give them some namespacing
```
state-machine.publishing.transitions.publish
state-machine.publishing.transitions.delete
state-machine.publishing.transitions.save_draft
```

Check one by one with 

`Gate::allows($transition)`

return array

My Model has a Method called

`getAuthorizedTransitions()`


My approach is namespacing my permissions like this

```
state-machine.[state machine name].[transitions].[transition name]
state-machine.[state machine name].[state].[state name]
```

**Comment by eduardoarandah** [comment]
## Didn't work with 

`        'do' => [Iluminate\Auth\Access\Gate::class, 'allows'],`

![imagen](https://user-images.githubusercontent.com/4065733/30725824-f9646f34-9f0c-11e7-94de-778aa21c03fd.png)

## Worked Ok with 

**Illuminate\Contracts\Auth\Access\Gate::class**

```
[
'on'   => 'rechazar',                  
'do'   => [Illuminate\Contracts\Auth\Access\Gate::class, 'allows'],
'args' => ['"transitions.exposicion.rechazar"'],
],                 
```

![imagen](https://user-images.githubusercontent.com/4065733/30725864-330b1fda-9f0d-11e7-907f-b9e0e39688b6.png)

**Comment by eduardoarandah** [comment]
Being able to do this in the config file would be great!

```
'guard'  => [
[                    
    'on'   => 'rechazar',
    'gate'=>'transitions.exposicion.rechazar',                    
],
[                    
    'on'   => 'aprobar',
    'gate'=>['transitions.exposicion.aprobar','"somethingElse"'],                    
],
```

Might be a just a shortcut to call the real function I guess

**Comment by sebdesign** [comment]
Indeed using the contract should work!

I like your ideas about authorization, I'll think about it and probably will integrate something in the package.

Someone could also use Gates the other way around, the Gate asks the state machine what it can/cannot do. E.g. if I want to use `@can('state-machine.publishing.transitions.publish', $model)` in my views  to ask if the state machine can go to `published` state from the current state.

**Comment by eduardoarandah** [comment]
Yes, absolutely. 

I'm managing it in a very convenient way with a **trait**

```php
<?php

namespace App\Traits;

trait Statable
{
    protected $stateMachine;

    public function stateMachine()
    {
        if (!$this->stateMachine) {
            $this->stateMachine = \StateMachine::get($this, $this->stateMachineName);
        }
        return $this->stateMachine;
    }

    public function stateKey()
    {
        return $this->stateMachine()->getState();
    }
    public function stateName()
    {
        return ucfirst(str_replace('_', ' ', $this->stateKey()));
    }
    public function stateAllowed()
    {
        return \Gate::allows('states.' . $this->stateMachineName . '.' . $this->stateKey());
    }
    public function stateAttribute($key)
    {
        return $this->stateConfig()[$this->stateKey()][$key];
    }
    public function stateConfig()
    {
        return config('state-machine.' . $this->stateMachineName . '.state_attributes');
    }
    public function transition($transition)
    {
        return $this->stateMachine()->apply($transition);
    }
    public function transitionAllowed($transition)
    {
        return $this->stateMachine()->can($transition);
    }
    public function transitions()
    {
        return $this->stateMachine()->getPossibleTransitions();
    }
    public function transitionsAuthorized()
    {
        return $this->stateMachine()->getPossibleTransitions();
    }
}
```

## in the model

```php
<?php

class Exposicion extends Model
{
    use CrudTrait;

    use Statable;
    private $stateMachineName = 'exposicion';

    //initial state
    protected $attributes = [
        'state' => 'enviado',
    ];
```

A couple of things to notice: 

- This code is useful to have a default state in case nothing is provided

```php
protected $attributes = [
        'state' => 'enviado',
];

```
- In practice, we need to have more **knowledge** about states and transitions, in this example I'm rendering a label with nice colors to show current state. 

```php
<?php

public function renderStateLabel()
    {
        $name  = $this->stateName();
        $class = $this->stateAttribute('class');

        return "<span class='label label-xs label-$class'>$name</span>";
    }
```

## This is the graph

```php
<?php

return [
    'exposicion' => [
        // class of your domain object
        'class'            => App\Models\Exposicion::class,

        // name of the graph (default is "default")
        'graph'            => 'exposicion',

        // property of your object holding the actual state (default is "state")
        'property_path'    => 'state',

        // list of all possible states
        'states'           => [
            'enviado',
            'se_solicitan_cambios',
            'no_aprobado',
            'aprobado',
            'confirmado',
        ],
        'state_attributes' => [
            'enviado'              => [
                'class' => 'default',
            ],
            'se_solicitan_cambios' => [
                'class' => 'warning',
            ],
            'no_aprobado'          => [
                'class' => 'danger',
            ],
            'aprobado'             => [
                'class' => 'primary',
            ],
            'confirmado'           => [
                'class' => 'success',
            ],
        ],

        // list of all possible transitions
        'transitions'      => [
            'no_aprobar'            => [
                'from' => ['enviado', 'aprobado'],
                'to'   => 'no_aprobado',
            ],
            'aprobar'               => [
                'from' => ['enviado', 'no_aprobado'],
                'to'   => 'aprobado',
            ],
            'solicitar_cambios'     => [
                'from' => ['enviado'],
                'to'   => 'se_solicitan_cambios',
            ],
            'hacer_cambios'         => [
                'from' => ['se_solicitan_cambios'],
                'to'   => 'enviado',
            ],
            'confirmar'             => [
                'from' => ['aprobado'],
                'to'   => 'confirmado',
            ],
            'cancelar_confirmacion' => [
                'from' => ['confirmado'],
                'to'   => 'aprobado',
            ],
        ],
      'transition_attributes' => [            
        ],

        // list of all callbacks
        'callbacks'        => [
            // will be called when testing a transition
            'guard'  => [
                'guard_on_no_aprobar'            => [
                    'on'   => 'no_aprobar',
                    'do'   => [Illuminate\Contracts\Auth\Access\Gate::class, 'allows'],
                    'args' => ['"transitions.exposicion.no_aprobar"'],
                ],
                'guard_on_aprobar'               => [
                    'on'   => 'aprobar',
                    'do'   => [Illuminate\Contracts\Auth\Access\Gate::class, 'allows'],
                    'args' => ['"transitions.exposicion.aprobar"'],
                ],
                'guard_on_solicitar_cambios'     => [
                    'on'   => 'solicitar_cambios',
                    'do'   => [Illuminate\Contracts\Auth\Access\Gate::class, 'allows'],
                    'args' => ['"transitions.exposicion.solicitar_cambios"'],
                ],
                'guard_on_hacer_cambios'         => [
                    'on'   => 'hacer_cambios',
                    'do'   => [Illuminate\Contracts\Auth\Access\Gate::class, 'allows'],
                    'args' => ['"transitions.exposicion.hacer_cambios"'],
                ],
                'guard_on_confirmar'             => [
                    'on'   => 'confirmar',
                    'do'   => [Illuminate\Contracts\Auth\Access\Gate::class, 'allows'],
                    'args' => ['"transitions.exposicion.confirmar"'],
                ],
                'guard_on_cancelar_confirmacion' => [
                    'on'   => 'cancelar_confirmacion',
                    'do'   => [Illuminate\Contracts\Auth\Access\Gate::class, 'allows'],
                    'args' => ['"transitions.exposicion.cancelar_confirmacion"'],
                ],
            ],

            // will be called before applying a transition
            'before' => [],

            // will be called after applying a transition
            'after'  => [],
        ],
    ],
];
```


# This is how it renders

![imagen](https://user-images.githubusercontent.com/4065733/30747450-f0531ca4-9f72-11e7-8224-d18d459f3e28.png)


# This is how to make transitions

![imagen](https://user-images.githubusercontent.com/4065733/30747416-cef0695e-9f72-11e7-9b41-7a6527c89595.png)

# Transitions render buttons dinamically

![imagen](https://user-images.githubusercontent.com/4065733/30747511-2cb75674-9f73-11e7-98a8-9517e22ecd2c.png)



# Blade
in blade, authorization would be

```
@if($model->stateAllowed())
@endif
```

I guess a blade directive would be nice, what do you think? @stateAllowed($model)

This is a trait based in this article https://gist.github.com/iben12/7e24b695421d92cbe1fec3eb5f32fc94

As you can see, I'm adding state_attributes and transition_attributes because we may need some knowledge apart from the state name, 

Example: 
for a Notification we may need the user and the subject
example: notify_user=>1, email_subject=>'something approved'


Give me your thoughts, I'm thinking about making this trait a package.

**Comment by sebdesign** [comment]
Hi @eduardoarandah ,

I'm working on the Gate functionality, and this is what I suggest:

```php
<?php

'guard_on_no_aprobar' => [
    'on' => 'no_aprobar',
    'can' => 'transitions.exposicion.no_aprobar',
],
```
The `can` accepts the ability that you have defined in `Gate:define()` or you policy method.
Also, in the `can` key you can pass an array of gates, and every one will be checked.

The `args` key should be optional, but if you pass `['object', 'event']` (or any combination of arguments) those will be passed to the parameters of the gate you have defined.
For instance, if you have a Policy for the model/object, you can pass `object` as an argument and the `Expocision` instance will be passed so your policy will be used.

What do you think?

**Comment by eduardoarandah** [comment]
THATS perfect! 

Also the verb “can” is perfect. Feels natural.

**Comment by mitjarobic** [comment]
Is the can verb implemented?

**Comment by sebdesign** [comment]
@mitjarobic not yet, I'm planning to release it this month.

**Comment by capricorn05** [comment]
HI @sebdesign ,
Did the can functionality you described above go live?
thanks

**Comment by sebdesign** [comment]
Hello folks,

I have tagged a new releases [v1.3.0](https://github.com/sebdesign/laravel-state-machine/releases/tag/v1.3.0) which implements the `can` keyword on callbacks.

Here is the documentation: https://github.com/sebdesign/laravel-state-machine#using-gates-and-policies.

Let me know if that works for you!
