### ISSUE TITLE
Declaration of methods from Dispatcher class must be compatible with Symfony EventDispatcherInterface interface

### ISSUE THREAD

**Issue by LucasLaurens** [sebdesign/laravel-state-machine#70]
### Context

I updated composer with `composer update`.
I ran the command `php ./vendor/bin/phpstan analyse -c phpstan.neon` to analyse my code. I received an error on this `Sebdesign\SM\Event\Dispatcher` file. The methods no longer correspond to the Symfony update.

> [!NOTE]
> This depreciation comes with the new version of Symfony e.g. `symfony/event-dispatcher:7.0.2`.

![Capture d’écran 2024-01-29 à 13 59 13](https://github.com/sebdesign/laravel-state-machine/assets/22150132/d7f45c71-5353-4679-9079-05e3d10bb4ef)

**Comment by LucasLaurens** [comment]
I could create a PULL REQUEST to see if there are any other similar issues. However, I don't have the permission yet.

**Comment by ABartelt** [comment]
I think PR #69 addresses this issue already 👍

**Comment by LucasLaurens** [comment]
> I think PR #69 addresses this issue already 👍

You're absolutely right. That's exactly right. I hadn't seen that much for myself. Thank you. So I'll wait for the PR to be validated.
