### ISSUE TITLE
Debug Command returns double configurations

### ISSUE THREAD

**Issue by eduardoarandah** [sebdesign/laravel-state-machine#8]
When running this command, returns two configurations: the one in your package plus the one in the app

Example:

**pa winzou:state-machine:debug**

```
 Which state machine would you like to know about? [graphA      (App\User - graphA)]:
  [0] graphA    (App\User - graphA)
  [1] exposicion        (App\Models\User - exposicion)
 >
```

I don't have any graphA or a model called App\User

My config file /config/state-machine.php is:

```

<?php

return [
    'exposicion' => [
        // class of your domain object
        'class'                 => App\Models\User::class,

        // name of the graph (default is "default")
        'graph'                 => 'exposicion',
```

function mergeConfigFrom() is the one causing trouble

/vendor/sebdesign/laravel-state-machine/src/ServiceProvider.php

```
 public function register()
    {
        $this->mergeConfigFrom(__DIR__.'/../config/state-machine.php', 'state-machine');

    }
```

**Comment by sebdesign** [comment]
That's a bug!

I just tagged a new version (v.1.2.3) with a fix.
